import osh

cap = osh.cap[40]
print(cap)

print('delta')
print(cap.delta)
print('----------------------------------------------')
print('destination')
print(cap.destination)
print('----------------------------------------------')
print('host')
print(cap.host)
print('----------------------------------------------')
print('info')
print(cap.info)
print('----------------------------------------------')
print('ip')
print(cap.ip)
print('----------------------------------------------')
print('length')
print(cap.length)
print('----------------------------------------------')
print('no')
print(cap.no)
print('----------------------------------------------')
print('protocol')
print(cap.protocol)
print('----------------------------------------------')
print('source')
print(cap.source)
print('----------------------------------------------')
print('stream')
print(cap.stream)
print('----------------------------------------------')
print('summary_line')
print(cap.summary_line)
print('----------------------------------------------')
print('time')
print(cap.time)
print('----------------------------------------------')
print('window')
print(cap.window)
print('----------------------------------------------')
