version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=ubuntu18
      - POSTGRES_PASSWORD=rusanow
      - POSTGRES_DB=flask_db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ubuntu18
      - POSTGRES_PASSWORD=rusanow
      - POSTGRES_DB=flask_db